### PR TITLE
Fix size of window on MacOS.

### PR DESCRIPTION
**Pull request by lkesteloot**
The API for NSWindow's creation has a contentRect parameter,
but it seems to be handled like a frameRect. So convert from
contentRect to frameRect first. Without this change the
top 20-ish lines of the image are under the title bar.

### CODE REVIEW

**Comment by lkesteloot** [comment]
I'm not super confident about this change, by the way. (Also I've not compiled it in-repo because I don't have tundra.) I don't know why my change should be necessary, so it's possible that in some situations the original code was correct.

**Comment by lkesteloot** [comment]
This is for issue #14.

**Comment by emoon** [comment]
Thanks! I will do some testing with this later today.

**Comment by emoon** [comment]
Sorry. I totally forgot about this one!

**Pull request merged**
